export const OPEN_NOTIFICATION = 'OPEN_NOTIFICATION';
export type OPEN_NOTIFICATION = typeof OPEN_NOTIFICATION;

export const CLOSE_NOTIFICATION = 'CLOSE_NOTIFICATION';
export type CLOSE_NOTIFICATION = typeof CLOSE_NOTIFICATION;
