const AUTH_SIGN_IN = 'AUTH_SIGN_IN';

const AUTH_GET_INFO = 'AUTH_GET_INFO';

const AUTH_SAVE_INFO = 'AUTH_SAVE_INFO';

const AUTH_SAVE_TOKEN = 'AUTH_SAVE_TOKEN';

const AUTH_CLEAN_INFO = 'AUTH_CLEAN_INFO';

const AUTH_SIGN_OUT = 'AUTH_SIGN_OUT';

const AUTH_ERROR = 'AUTH_ERROR';

export {
  AUTH_SIGN_IN,
  AUTH_GET_INFO,
  AUTH_SAVE_INFO,
  AUTH_SAVE_TOKEN,
  AUTH_CLEAN_INFO,
  AUTH_SIGN_OUT,
  AUTH_ERROR,
};
